### ISSUE TITLE
bonus - testovani: Negativní testy

### ISSUE THREAD

**Issue by encukou** [jiri-one/Kosoctverci#1]
Je potřeba otestovat co se stane, když funkce `vyhodnot` dostane jiný vstup než očekává, třeba `"papir"` s krátkým i nebo `"metal"` :metal:

**Comment by jiri-one** [comment]
Zatím nezavírám, protože předpokládám, že budeš chtít, abych řešil nějaké vyjímky raději ... :).

**Comment by encukou** [comment]
To budu :)
`None` znamená remízu; u špatného vstupu by funkce remízu hlásit neměla.

**Comment by jiri-one** [comment]
commit 857894a přidal správnou remízu, takže zavírám
