### ISSUE TITLE
bonus - testovani: Parametrické testy

### ISSUE THREAD

**Issue by encukou** [jiri-one/Kosoctverci#4]
Aktuálně se v testovací funkci opakuje několikrát po sobě `assert`: https://github.com/jiri-one/Kosoctverci/blob/28b756ef88c1f322927eeae646a595c136ec5205/bonus%20-%20testovani/test_kamen_nuzky_papir.py#L4-L13

To není ideální: `assert ...` funguje jako `if not ...: raise AssertionError()`, neboli když test neprojde, vyhodí se výjimka. A po vyhození výjimky se neprovede zbytek funkce, takže nevíme jestli ty další kontroly prošly.
Proto, pokud to nějak rozumně jde, je lepší mít v každé testovací funkci jen jeden `assert`.

V tomhle případě se na to dají použít *parametrické testy*. Pomocí speciálního dekorátoru `pytest.mark.parametrize` řekneme Pytestu, že má jednu funkci zavolat několikrát, pokaždé s jinými argumenty.
Dekorátor potřebuje dva kousky informace:
* jméno argument, které bude nastavovat
* seznam jednotlivých hodnot

Funuje to takhle; vyzkoušejte:
```python
import pytest 

@pytest.mark.parametrize("a", (1, 2, 3, 4))
def test_pricteni_2(a):
    assert 2 + a > a
```
Doporučuju vyzkoušet s přepínačem `-v`, který ukáže jména jednotlivých testů.

## Sady víc proměnných

Často je potřeba měnit víc proměnných najednou, typicky vstup a očekávaný výstup. Pro tyhle případy lze dát dekorátoru `parametrize` trochu složitější data:
* *n*-tici jmen argumentů, které bude nastavovat
* seznam *n*-tic jednotlivých hodnot

Například:
```python
@pytest.mark.parametrize(
    ("a", "b", "ocekavany_vysledek"),
    [
        (1, 2, 3),
        (0, 0, 0),
        ("a", "b", "ab"),
        (3, 4, "tady je schvalne chyba v testu"),
        (-3, 7, 4),
        (4, 6, "dalsi chyba v testu"),
    ]
)
def test_secitani(a, b, ocekavany_vysledek):
    vysledek = a + b
    assert vysledek == ocekavany_vysledek
```

## Každý s každým

Dekorátor lze použít i několikrát; pak se každá hodnota z jednoho volání použije s každou hodnotou z toho dalšího. Následující funkce tak přidá hned 9 testů 
```
@pytest.mark.parametrize("a", (1, 2, 3))
@pytest.mark.parametrize("b", (4, 5, 6))
def test_secitani_kladnych_cisel(a, b):
    assert a + b > a
    assert a + b > b
```

## Úkol

Která varianta parametrických testů bude nejlepší pro testování kámen-nůžky-papír? Zkuste ji použít.

**Comment by jiri-one** [comment]
tak vyřešeno a čekám na připomínky :). Zatím nezavírám ...

**Comment by encukou** [comment]
Parametrické testy vypadají dobře :)
