### ISSUE TITLE
Pojmenovat testy

### ISSUE THREAD

**Issue by encukou** [jiri-one/Kosoctverci#5]
Když pustím pytest s `-v`, vidím jména testů `test_vyhodnot`, `test2_vyhodnot`, `test3_vyhodnot`. To mi o tom, co se testuje, nic moc neřekne.
Zkuste přijít na jména, která líp vystihnou co který test dělá.

**Comment by encukou** [comment]
Tohle vypadá že je spravené v a8d3bbd99c08a314b4d6d360af2efa0c0b09c357. Super!
Pořád tam ale ještě je `test_mix_inputs` a `test2_mix_inputs`. Čím se liší? Dá se ten rozdíl zakomponovat do jména?

---

Tip: do commitu (nebo pull requestu) můžeš napsat řádek jako:
```
Fixes: #5
Fixes: https://github.com/jiri-one/Kosoctverci/issues/5
Solves: #5
```
nebo [podobně](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). GitHub pak zavře *issue* `#5` automaticky.

(Verze s celou adresou je lepší v tom, že kdyby jednou projekt přešel na jiný systém hlídání chyb než GitHub, bude jasné co to číslo znamená.)

**Comment by jiri-one** [comment]
solved with a2897df
